apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aedwf.fullname" . }}-datadir
  labels:
    {{- include "aedwf.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storageAccessMode | default "ReadWriteMany" }}
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: 1G
