apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aedwf.fullname" . }}-datadir
  labels:
    {{- include "aedwf.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 1G
