---
# tasks file for edf6_master
- name: install deps
  dnf:
    name:
      - mapr-hiveserver2
      - mapr-httpfs
      - mapr-spark-historyserver
      - mapr-spark-thriftserver
      - mapr-resourcemanager
      - mapr-historyserver	
      - mapr-timelineserver	
      - mapr-hue
      - mapr-hivemetastore
      - mapr-sentry
      - mapr-kafka
      - mapr-ksql
      - mapr-kafka-connect-jdbc	
      - mapr-kafka-rest	
      - mapr-hbase-rest
      - mapr-hbasethrift
      - mapr-spark-historyserver	
      - mapr-spark-thriftserver
      - mapr-livy

- name: get hostname
  command: hostname --fqdn
  register: hostname_out

- set_fact:
    host_fqdn: "{{ hostname_out.stdout }}"

- name: install hue config
  template:
    src: hue.ini.tmpl
    dest: /opt/mapr/hue/hue-4.6.0/desktop/conf/hue.ini

- name: login
  shell:
    cmd: echo mapr | maprlogin password
  become: true
  become_user: mapr

- name: create maprdb directory
  shell:
    cmd: /opt/mapr/hadoop/hadoop-2.7.6/bin/hadoop dfs -mkdir -p /maprdb
  become: true
  become_user: mapr

- name: initialize metastore
  shell:
    cmd: "/opt/mapr/hive/hive-2.3/bin/schematool -dbType {{ metastore_initdb_engine }} -initSchema"
  ignore_errors: true
  become: true
  become_user: mapr

- name: refresh config
  command: "/opt/mapr/server/configure.sh -R {{ configure_opts }}"
  when: skip_configure == false


