---
# tasks file for edf6_pushconfig
- name: extract core configs
  unarchive:
    src: cluster_initconfig.tar.bz2
    dest: /opt/mapr/

- name: allow overcommit
  lineinfile:
    path: /opt/mapr/conf/warden.conf
    line: "enable.overcommit=true"
    create: yes
