apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aedwf.fullname" . }}-redis-config
  labels:
    {{- include "aedwf.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis.conf: |
    {{- include "redis-config" . | nindent 4 }}
  sentinel.conf: |
    {{- include "redis-sentinel-config" . | nindent 4 }}
