apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aedwf.fullname" . }}-redis
  labels:
    {{- include "aedwf.labels" . | nindent 4 }}
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aedwf.selectorLabels" . | nindent 6 }}
      component: redis
  serviceName: {{ include "aedwf.fullname" . }}-redis
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aedwf.selectorLabels" . | nindent 8 }}
        component: redis
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aedwf.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "aedwf.fullname" . }}-redis-config
          secret:
            secretName: {{ include "aedwf.fullname" . }}-redis-config
        - name: {{ include "aedwf.fullname" . }}-redis-log
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.redis_image.repository }}:{{ .Values.redis_image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redis_image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "aedwf.fullname" . }}-redis-config
              mountPath: "/etc/redis"
            - name: {{ include "aedwf.fullname" . }}-redis
              mountPath: "/var/lib/redis"
            - name: {{ include "aedwf.fullname" . }}-redis-log
              mountPath: "/var/log/redis"

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "aedwf.fullname" . }}-redis
      spec:
        accessModes: 
          - {{ .Values.storageAccessMode | default "ReadWriteMany" }}
        resources:
          requests:
            storage: 5G
