apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hivemetastore.fullname" . }}-init
  labels:
    {{- include "hivemetastore.labels" . | nindent 4 }}
spec:
  template:
    spec:
      volumes:
        - name: {{ include "hivemetastore.fullname" . }}-config
          secret:
            secretName: {{ include "hivemetastore.fullname" . }}-config
        - name: {{ include "hivemetastore.fullname" . }}-datadir
          emptyDir: {}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_TYPE
              value: {{ .Values.hive.metastore_db_type }}
          args: ["schematool", "-initSchema"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "hivemetastore.fullname" . }}-config
              mountPath: "/etc/hive/"
            - name: {{ include "hivemetastore.fullname" . }}-datadir
              mountPath: "/opt/apache/hive/work-dir"
  backoffLimit: 10
  completions: 1
