apiVersion: v1
kind: Service
metadata:
  name: {{ include "hivemetastore.fullname" . }}
  labels:
    {{- include "hivemetastore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metastore
      protocol: TCP
      name: metastore
  selector:
    {{- include "hivemetastore.selectorLabels" . | nindent 4 }}
