---
# tasks file for aecdp
- name: install python interpreter
  dnf: 
    name: 
      - python3
      - python3-devel
      - python3-pyyaml

- name: create virtualenv
  command: python3 -m venv /opt/ansible_virtualenv/
  args:
    creates: /opt/ansible_virtualenv/bin/pip 

- name: setup virtualenv libraries
  pip:
    name:
      - boto3
      - botocore
      - kubernetes
      - pyyaml
    executable: /opt/ansible_virtualenv/bin/pip

- name: install repo
  kubernetes.core.helm_repository:
    name: "{{ repo_name }}"
    repo_url: "{{ repo_url }}"

- name: update repo
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: install registry
  kubernetes.core.helm:
    name: registry
    chart_ref: "{{ repo_name }}/registry"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "registry.{{ ingress_domain }}"
      registry:
        user: "{{ registry_user }}"
        password: "{{ registry_password }}"

- name: install minio
  kubernetes.core.helm:
    name: minio
    chart_ref: "{{ repo_name }}/minio"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "minio.{{ ingress_domain }}"
        console_host: "minio-console.{{ ingress_domain }}"
      minio:
        root_user: "{{ minio_user }}"
        root_password: "{{ minio_password }}"
        instance_storage: "{{ minio_storage_size }}"

- name: install citus
  kubernetes.core.helm:
    name: citus
    chart_ref: "{{ repo_name }}/citus"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"

- name: install gitserver
  kubernetes.core.helm:
    name: gitserver
    chart_ref: "{{ repo_name }}/gitserver"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "git.{{ ingress_domain }}"
      git:
        gitweb_password: "{{ dag_git_password }}"

- name: create buckets
  amazon.aws.s3_bucket:
    name: "{{ item }}"
    s3_url: "https://minio.{{ ingress_domain }}"
    aws_access_key: "{{ minio_user }}"
    aws_secret_key: "{{ minio_password }}"
    validate_certs: no
  with_items:
    - spark
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python

- name: create directories
  amazon.aws.s3_object:
    object: "{{ item }}"
    bucket: spark
    mode: create
    s3_url: "https://minio.{{ ingress_domain }}"
    aws_access_key: "{{ minio_user }}"
    aws_secret_key: "{{ minio_password }}"
    validate_certs: no
  with_items:
    - event_log/
    - tablespace/
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python


- name: create metastore database
  kubernetes.core.k8s_exec:
    namespace: "{{ release_namespace }}"
    pod: citus
    command: "createdb_with_user.sh -d {{ metastore_db_name }} -u {{ metastore_db_user }} -p {{ metastore_db_password }}"
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python


- name: install metastore
  kubernetes.core.helm:
    name: hivemetastore
    chart_ref: "{{ repo_name }}/hivemetastore"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      hive:
        metastore_db_url: "jdbc:postgresql://{{ metastore_db_host }}:{{ metastore_db_port }}/{{ metastore_db_name }}"
        metastore_db_driver: org.postgresql.Driver
        metastore_db_user: "{{ metastore_db_user }}"
        metastore_db_password: "{{ metastore_db_password }}"
        metastore_db_type: postgres
        metastore_warehouse_dir: s3a://spark/tablespace/
      s3a:
        endpoint: http://minio:9000
        access_key: "{{ minio_user }}"
        secret_key: "{{ minio_password }}"


- name: install spark
  kubernetes.core.helm:
    name: spark3
    chart_ref: "{{ repo_name }}/spark3"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      spark:
        hive_metastore_uri: thrift://hivemetastore:9083
        deploy_thrift: true
        k8s_namespace: "{{ release_namespace }}"
      ingress:
        thrift_host: "sparksql.{{ ingress_domain }}"
      s3a:
        endpoint: http://minio:9000
        access_key: "{{ minio_user }}"
        secret_key: "{{ minio_password }}"
      image:
        tag: "{{ spark_image_tag | default(omit) }}"


- name: create superset database
  kubernetes.core.k8s_exec:
    namespace: "{{ release_namespace }}"
    pod: citus
    command: "createdb_with_user.sh -d {{ aedv_db_name }} -u {{ aedv_db_user }} -p {{ aedv_db_password }}"
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python


- name: install superset
  kubernetes.core.helm:
    name: aedv
    chart_ref: "{{ repo_name }}/aedv"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "superset.{{ ingress_domain }}"
      superset:
        secret_key: secretkey
        db_uri: "postgresql+psycopg2://{{ aedv_db_user }}:{{ aedv_db_password }}@{{ aedv_db_host }}:{{ aedv_db_port }}/{{ aedv_db_name }}"

- name: create git repo
  kubernetes.core.k8s_exec:
    namespace: "{{ release_namespace }}"
    pod: gitserver
    command: newrepo myproject
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python

- name: create airflow database
  kubernetes.core.k8s_exec:
    namespace: "{{ release_namespace }}"
    pod: citus
    command: "createdb_with_user.sh -d {{ aedwf_db_name }} -u {{ aedwf_db_user }} -p {{ aedwf_db_password }}"

  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python

- name: install airflow
  kubernetes.core.helm:
    name: aedwf
    chart_ref: "{{ repo_name }}/aedwf"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "airflow.{{ ingress_domain }}"
      airflow:
        fernet_key: "{{ fernet_key }}"
        secret_key: "{{ secret_key }}"
        default_timezone: "{{ timezone }}"
        dag_git_repository: "{{ dag_git_repository }}"
        dag_git_username: "{{ dag_git_username }}"
        dag_git_password: "{{ dag_git_password }}"
        dag_git_branch: "{{ dag_git_branch }}"
        db_uri: "postgresql+psycopg2://{{ aedwf_db_user }}:{{ aedwf_db_password }}@{{ aedwf_db_host }}:{{ aedwf_db_port }}/{{ aedwf_db_name }}"
      spark:
        secret_name: spark3-config

- name: install jupyter
  kubernetes.core.helm:
    name: jupyterhub
    chart_ref: "{{ repo_name }}/jupyterhub"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "jupyter.{{ ingress_domain }}"
      spark:
        secret_name: spark3-config
      airflow:
        secret_name: aedwf-config
