---
# tasks file for aecdp
- name: install python interpreter
  dnf: 
    name: 
      - python3
      - python3-devel
      - python3-pyyaml

- name: create virtualenv
  command: python3 -m venv /opt/ansible_virtualenv/
  args:
    creates: /opt/ansible_virtualenv/bin/pip 

- name: setup virtualenv libraries
  pip:
    name:
      - boto3
      - botocore
      - kubernetes
      - pyyaml
    executable: /opt/ansible_virtualenv/bin/pip

- name: install repo
  kubernetes.core.helm_repository:
    name: "{{ repo_name }}"
    repo_url: "{{ repo_url }}"

- name: update repo
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: install registry
  kubernetes.core.helm:
    name: registry
    chart_ref: "{{ repo_name }}/registry"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "registry.{{ ingress_domain }}"
      registry:
        user: "{{ registry_user }}"
        password: "{{ registry_password }}"
        pvc_size: "{{ registry_storage_size | default(omit) }}"
      storageClass: "{{ registry_storage_class | default(omit) }}"
      storageAccessMode: "{{ registry_storage_accessmode | default(omit) }}"
  when: install_registry == true 

- name: install minio
  kubernetes.core.helm:
    name: minio
    chart_ref: "{{ repo_name }}/minio"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "minio.{{ ingress_domain }}"
        console_host: "minio-console.{{ ingress_domain }}"
      minio:
        root_user: "{{ minio_user }}"
        root_password: "{{ minio_password }}"
        instance_storage: "{{ minio_storage_size }}"
      storageClass: "{{ minio_storage_class | default(omit) }}"
      storageAccessMode: "{{ minio_storage_accessmode | default(omit) }}"

  when: install_minio == true

- name: install citus
  kubernetes.core.helm:
    name: citus
    chart_ref: "{{ repo_name }}/citus"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      storageClass: "{{ citus_storage_class | default(omit) }}"
      storageAccessMode: "{{ citus_storage_accessmode | default(omit) }}"

  when: install_citus == true 

- name: install gitserver
  kubernetes.core.helm:
    name: gitserver
    chart_ref: "{{ repo_name }}/gitserver"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "git.{{ ingress_domain }}"
      git:
        gitweb_password: "{{ dag_git_password }}"
      storageAccessMode: "{{ gitserver_storage_accessmode | default(omit) }}"

- name: create buckets
  amazon.aws.s3_bucket:
    name: "{{ item }}"
    s3_url: "{{ s3_url }}"
    aws_access_key: "{{ s3_access_key }}"
    aws_secret_key: "{{ s3_secret_key }}"
    validate_certs: "{{ validate_certs }}"
  with_items:
    - "{{ warehouse_bucket_name }}"
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python

- name: create directories
  amazon.aws.s3_object:
    object: "{{ item }}"
    bucket: "{{ warehouse_bucket_name }}"
    mode: create
    s3_url: "{{ s3_url }}"
    aws_access_key: "{{ s3_access_key }}"
    aws_secret_key: "{{ s3_secret_key }}"
    validate_certs: "{{ validate_certs }}"
  with_items:
    - event_log/
    - tablespace/
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python

- name: 
  kubernetes.core.helm:
    name: dex
    chart_ref: "{{ repo_name }}/dexidp"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "sso.{{ ingress_domain }}"
      serviceAccount:
        create: true
        name: "{{ dex_service_account | default(omit) }}"

  when: install_dex == true

- name: create metastore database
  kubernetes.core.k8s_exec:
    namespace: "{{ release_namespace }}"
    pod: citus-0
    command: "createdb_with_user.sh -d {{ metastore_db_name }} -u {{ metastore_db_user }} -p {{ metastore_db_password }}"
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python
  when: install_citus == true

- name: install metastore
  kubernetes.core.helm:
    name: hivemetastore
    chart_ref: "{{ repo_name }}/hivemetastore"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      hive:
        metastore_db_url: "{{ metastore_db_proto }}://{{ metastore_db_host }}/{{ metastore_db_name }}"
        metastore_db_driver: "{{ metastore_db_driver }}"
        metastore_db_user: "{{ metastore_db_user }}"
        metastore_db_password: "{{ metastore_db_password }}"
        metastore_db_type: "{{ metastore_db_type }}"
        metastore_warehouse_dir: "s3a://{{ warehouse_bucket_name }}/tablespace/"
        metastore_java_options: "{{ metastore_java_options }}"
      s3a:
        endpoint: "{{ s3_url }}"
        access_key: "{{ s3_access_key }}"
        secret_key: "{{ s3_secret_key }}"

- name: install spark
  kubernetes.core.helm:
    name: spark3
    chart_ref: "{{ repo_name }}/spark3"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      spark:
        hive_metastore_uri: thrift://hivemetastore-0.hivemetastore:9083
        deploy_thrift: true
        k8s_namespace: "{{ release_namespace }}"
        executor_java_options: "{{ spark_executor_java_options | default(omit) }}"
        driver_java_options: "{{ spark_driver_java_options | default(omit) }}"
        bucket: "{{ warehouse_bucket_name }}"
      ingress:
        thrift_host: "sparksql.{{ ingress_domain }}"
      s3a:
        endpoint: "{{ s3_url }}"
        access_key: "{{ s3_access_key }}"
        secret_key: "{{ s3_secret_key }}"
      image:
        tag: "{{ spark_image_tag | default(omit) }}"
      serviceAccount:
        create: true
        name: "{{ spark_service_account | default(omit) }}"

- name: create superset database
  kubernetes.core.k8s_exec:
    namespace: "{{ release_namespace }}"
    pod: citus-0
    command: "createdb_with_user.sh -d {{ aedv_db_name }} -u {{ aedv_db_user }} -p {{ aedv_db_password }}"
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python
  when: install_citus == true

- name: install superset
  kubernetes.core.helm:
    name: aedv
    chart_ref: "{{ repo_name }}/aedv"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "superset.{{ ingress_domain }}"
      superset:
        secret_key: "{{ secret_key }}"
        db_uri: "{{ aedv_db_proto }}://{{ aedv_db_user }}:{{ aedv_db_password }}@{{ aedv_db_host }}/{{ aedv_db_name }}"
      storageAccessMode: "{{ aedv_storage_accessmode | default(omit) }}"

- name: create git repo
  kubernetes.core.k8s_exec:
    namespace: "{{ release_namespace }}"
    pod: gitserver-0
    command: newrepo myproject
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python

- name: create airflow database
  kubernetes.core.k8s_exec:
    namespace: "{{ release_namespace }}"
    pod: citus-0
    command: "createdb_with_user.sh -d {{ aedwf_db_name }} -u {{ aedwf_db_user }} -p {{ aedwf_db_password }}"
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python
  when: install_citus == true

- name: install airflow
  kubernetes.core.helm:
    name: aedwf
    chart_ref: "{{ repo_name }}/aedwf"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "airflow.{{ ingress_domain }}"
      airflow:
        fernet_key: "{{ fernet_key }}"
        secret_key: "{{ secret_key }}"
        default_timezone: "{{ timezone }}"
        dag_git_repository: "{{ dag_git_repository }}"
        dag_git_username: "{{ dag_git_username }}"
        dag_git_password: "{{ dag_git_password }}"
        dag_git_branch: "{{ dag_git_branch }}"
        db_uri: "{{ aedwf_db_proto }}://{{ aedwf_db_user }}:{{ aedwf_db_password }}@{{ aedwf_db_host }}/{{ aedwf_db_name }}"
      spark:
        secret_name: spark3-config
      storageClass: "{{ aedwf_storage_class | default(omit) }}"
      storageAccessMode: "{{ aedwf_storage_accessmode | default(omit) }}"
      serviceAccount:
        create: true
        name: "{{ aedwf_service_account | default(omit) }}"


- name: create jupyterhub database
  kubernetes.core.k8s_exec:
    namespace: "{{ release_namespace }}"
    pod: citus-0
    command: "createdb_with_user.sh -d {{ jupyterhub_db_name }} -u {{ jupyterhub_db_user }} -p {{ jupyterhub_db_password }}"
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python
  when: install_citus == true

- name: install jupyter
  kubernetes.core.helm:
    name: jupyterhub
    chart_ref: "{{ repo_name }}/jupyterhub"
    release_namespace: "{{ release_namespace }}"
    create_namespace: true
    wait: true
    timeout: "{{ helm_timeout }}"
    values:
      ingress:
        host: "jupyter.{{ ingress_domain }}"
      spark:
        secret_name: spark3-config
      airflow:
        secret_name: aedwf-config
      jupyterhub:
        db_uri: "{{ jupyterhub_db_proto }}://{{ jupyterhub_db_user }}:{{ jupyterhub_db_password }}@{{ jupyterhub_db_host }}/{{ jupyterhub_db_name }}"
        nb_storage_class: "{{ jupyterhub_nb_storage_class | default(omit) }}"
        nb_storage_capacity: "{{ jupyterhub_nb_storage_capacity | default(omit) }}"
      storageAccessMode: "{{ jupyterhub_storage_accessmode | default(omit) }}"
      storageClass: "{{ jupyterhub_storage_class | default(omit) }}"
      serviceAccount:
        create: true
        name: "{{ jupyterhub_service_account | default(omit) }}"


- name: create warehouse database
  kubernetes.core.k8s_exec:
    namespace: "{{ release_namespace }}"
    pod: citus-0
    command: "createdb_with_user.sh -d {{ warehouse_db_name }} -u {{ warehouse_db_user }} -p {{ warehouse_db_password }}"
  vars:
    ansible_python_interpreter: /opt/ansible_virtualenv/bin/python
  when: install_citus == true


