{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aedv.fullname" . }}-tls
  labels:
    {{- include "aedv.labels" . | nindent 4 }}
stringData:
  tls.crt: |
    {{- include "server.crt" . | nindent 4 }}
  tls.key: |
    {{- include "server.key" . | nindent 4 }}
type: kubernetes.io/tls
