apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aedwf.fullname" . }}-scheduler
  labels:
    {{- include "aedwf.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aedwf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aedwf.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aedwf.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "aedwf.fullname" . }}-config
          secret:
            secretName: {{ include "aedwf.fullname" . }}-config
        - name: {{ include "aedwf.fullname" . }}-datadir
          emptyDir: {}
        - name: {{ include "aedwf.fullname" . }}-logdir
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["scheduler"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "aedwf.fullname" . }}-config
              mountPath: "/etc/apache-airflow"
            - name: {{ include "aedwf.fullname" . }}-datadir
              mountPath: "/var/lib/apache-airflow"
            - name: {{ include "aedwf.fullname" . }}-logdir
              mountPath: "/var/log/apache-airflow"
          env:
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "aedwf.fullname" . }}-secrets
                  key: fernet-key


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

