{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aedwf.fullname" . }}-secrets
  labels:
    {{- include "aedwf.labels" . | nindent 4 }}
type: Opaque
stringData:
  fernet-key: {{ quote .Values.airflow.fernet_key }}
  git-username: {{ quote .Values.airflow.dag_git_username }}
  git-password: {{ quote .Values.airflow.dag_git_password }}
