{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aedwf.fullname" . }}-config
  labels:
    {{- include "aedwf.labels" . | nindent 4 }}
type: Opaque
stringData:
  airflow.cfg: |
    {{- include "airflow-config" . | nindent 4 }}
  webserver_config.py: |
    {{- include "airflow-webserver-config" . | nindent 4 }}
