{{- include "require" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aedwf.fullname" . }}-worker
  labels:
    {{- include "aedwf.labels" . | nindent 4 }}
    component: worker
spec:
  clusterIP: None
  selector:
    {{- include "aedwf.selectorLabels" . | nindent 4 }}
    component: worker
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aedwf.fullname" . }}-worker
  labels:
    {{- include "aedwf.labels" . | nindent 4 }}
    component: worker
spec:
  serviceName: {{ include "aedwf.fullname" . }}-worker
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.worker_instances }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aedwf.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aedwf.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      setHostnameAsFQDN: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aedwf.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "aedwf.volumes" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["worker"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "aedwf.volumeMounts" . | nindent 12 }}
          env:
            {{- include "aedwf.env" . | nindent 12 }}
          securityContext:
            capabilities:
              add: ["NET_BIND_SERVICE", "NET_ADMIN"]

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

