apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterhub.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "jupyterhub.selectorLabels" . | nindent 4 }}
