apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jupyterhub.fullname" . }}-config
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  jupyterhub_config.py: |
    {{- include "jupyterhub.config" . | nindent 4 }}

