apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jupyterhub.fullname" . }}-secrets
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.jupyter.token }}
  auth-token: {{ quote .Values.jupyter.token }}
  {{- end }}
