apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aedv.fullname" . }}-web
  labels:
    {{- include "aedv.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.web_instances }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aedv.selectorLabels" . | nindent 6 }}
      component: web
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aedv.selectorLabels" . | nindent 8 }}
        component: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aedv.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "aedv.fullname" . }}-config
          secret:
            secretName: {{ include "aedv.fullname" . }}-config
        - name: {{ include "aedv.fullname" . }}-datadir
          emptyDir: {}
        - name: {{ include "aedv.fullname" . }}-logdir
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["start"]
          ports:
            - name: http
              containerPort: 8999
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "aedv.fullname" . }}-config
              mountPath: "/etc/apache-superset"
            - name: {{ include "aedv.fullname" . }}-datadir
              mountPath: "/var/lib/apache-superset"
            - name: {{ include "aedv.fullname" . }}-logdir
              mountPath: "/var/log/apache-superset"
          env:
            - name: SUPERSET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "aedv.fullname" . }}-secrets
                  key: secret-key

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

