apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aedv.fullname" . }}-secrets
  labels:
    {{- include "aedv.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ quote .Values.superset.secret_key }}
  previous-secret-key: {{ quote .Values.superset.previous_secret_key }}
