{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aedv.fullname" . }}-config
  labels:
    {{- include "aedv.labels" . | nindent 4 }}
type: Opaque
stringData:
  superset_config.py: |
    {{- include "superset-config" . | nindent 4 }}
