apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aedv.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aedv.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ quote .Values.superset.secret_key }}
