apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aedv.fullname" . }}-redis-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aedv.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis.conf: |
    {{- include "redis-config" . | nindent 4 }}
  sentinel.conf: |
    {{- include "redis-sentinel-config" . | nindent 4 }}
