apiVersion: v1
kind: Service
metadata:
  name: {{ include "aedv.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aedv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.redis_service.port }}
      targetPort: {{ .Values.redis_service.targetPort }}
      protocol: TCP
      name: redis
  selector:
    {{- include "aedv.selectorLabels" . | nindent 4 }}
    component: redis
