apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hive-metastore.fullname" . }}
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hive-metastore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hive-metastore.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hive-metastore.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "hive-metastore.fullname" . }}-config
          secret:
            secretName: {{ include "hive-metastore.fullname" . }}-config
        - name: {{ include "hive-metastore.fullname" . }}-datadir
          emptyDir: {}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["metastore", "-p", {{ .Values.hive.metastore_port | default "9083" | quote }}]
          #          args: ["noop"]
          ports:
            - name: metastore
              containerPort: {{ .Values.hive.metastore_port | default "9083" }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.hive.metastore_port | default "9083" }}
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket: 
              port: {{ .Values.hive.metastore_port | default "9083" }}
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: {{ include "hive-metastore.fullname" . }}-config
              mountPath: "/etc/hive/"
            - name: {{ include "hive-metastore.fullname" . }}-datadir
              mountPath: "/opt/apache/hive/work-dir"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
