apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive-metastore.fullname" . }}-config
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
type: Opaque
stringData:
  hive-site.xml:
    {{- include "hive-site" . | nindent 4 }}

