apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark3.fullname" . }}
  labels:
    {{- include "spark3.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "spark3.selectorLabels" . | nindent 4 }}

