apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark3.fullname" . }}-master-head
  labels:
    {{- include "spark3.labels" . | nindent 4 }}
    component: master-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7077
      targetPort: spark
      protocol: TCP
      name: spark
    - port: 8088
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spark3.selectorLabels" . | nindent 4 }}
    component: master
