apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark3.fullname" . }}-config
  labels:
    {{- include "spark3.labels" . | nindent 4 }}
type: Opaque
stringData:
  spark-defaults.conf: |
    {{- include "spark-defaults" . | nindent 4 }}
  spark-env.sh: |
    {{- include "spark-env" . | nindent 4 }}
  hive-site.xml:
    {{- include "hive-site" . | nindent 4 }}
  beeline-site.xml:
    {{- include "beeline-site" . | nindent 4 }}

