{{- include "require" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark3.fullname" . }}-client
  labels:
    {{- include "spark3.labels" . | nindent 4 }}
    component: client
spec:
  clusterIP: None
  selector:
    {{- include "spark3.selectorLabels" . | nindent 4 }}
    component: client
---

apiVersion: v1
kind: Pod
metadata:
  name: {{ include "spark3.fullname" . }}-client
  labels:
    {{- include "spark3.labels" . | nindent 4 }}
    component: client
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceAccountName: {{ include "spark3.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  volumes:
    {{- include "spark3.volumes" . | nindent 4 }}
  hostname: {{ include "spark3.fullname" . }}-client
  setHostnameAsFQDN: true
  containers:
    - name: {{ .Chart.Name }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      args: ['/usr/bin/tail', '-f', '/dev/null']
      volumeMounts:
        {{- include "spark3.volume-mounts" . | nindent 8 }}
      env:
        {{- include "spark3.env" . | nindent 8 }}
        {{- include "spark3.client-env" . | nindent 8 }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
