{{- include "require" . -}}
{{- if .Values.spark.deploy_cluster -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "spark3.fullname" . }}-master
  labels:
    {{- include "spark3.labels" . | nindent 4 }}
    component: master
spec:
  serviceName: {{ include "spark3.fullname" . }}-master
  replicas: 1
  selector:
    matchLabels:
      {{- include "spark3.selectorLabels" . | nindent 6 }}
      component: master
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spark3.selectorLabels" . | nindent 8 }}
        component: master
    spec:
    
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spark3.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "spark3.volumes" . | nindent 8 }}
      setHostnameAsFQDN: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["/usr/sbin/spark3-master"]
          ports:
            - name: spark
              containerPort: 7077
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            {{- include "spark3.volume-mounts" . | nindent 12 }}
          env:
            {{- include "spark3.env" . | nindent 12 }}
            - name: SPARK_MASTER_HOST
              value: 0.0.0.0
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    
{{- end }}
