apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "registry.fullname" . }}-data
spec:
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.registry.pvc_size | required "registry.pvc_size is required" }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "registry.fullname" . }}-auths
spec:
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
