{{- include "require" . -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "gitserver.fullname" . }}
  labels:
    {{- include "gitserver.labels" . | nindent 4 }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceAccountName: {{ include "gitserver.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  volumes:
    {{- include "gitserver.volumes" . | nindent 4 }}
  containers:
    - name: {{ .Chart.Name }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      args: ["sshd"]
      env: 
        {{- include "gitserver.env" . | nindent 8 }}
      ports:
        - name: sshd
          containerPort: 22
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: 22
        initialDelaySeconds: 15
        periodSeconds: 30
      readinessProbe:
        tcpSocket:
          port: 22
        initialDelaySeconds: 5
        periodSeconds: 15
      volumeMounts:
        {{- include "gitserver.volumeMounts" . | nindent 8 }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
