apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gitserver.fullname" . }}-data
spec:
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.git.pvc_size | required "git.pvc_size is required" }}
