{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitserver.fullname" . }}-secret
  labels:
    {{- include "gitserver.labels" . | nindent 4 }}
type: Opaque
stringData:
  ssh_public_keys: {{ .Values.git.ssh_public_keys }}
  gitweb_password: {{ .Values.git.gitweb_password }}
  gitweb_user: {{ .Values.git.gitweb_user | default "git" }}
