apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-secrets
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  root_user: {{ quote .Values.minio.root_user }}
  root_password: {{ quote .Values.minio.root_password }}

