apiVersion: v1
kind: Service
metadata:
  name: {{ include "citus.fullname" . }}
  labels:
    {{- include "citus.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "citus.selectorLabels" . | nindent 4 }}
