apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "citus.fullname" . }}-init
  labels:
    {{- include "citus.labels" . | nindent 4 }}
spec:
  template:
    spec:
      volumes:
        - name: {{ include "citus.fullname" . }}-datadir
          persistentVolumeClaim:
            claimName: {{ include "citus.fullname" . }}-data
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["initdb"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "citus.fullname" . }}-datadir
              mountPath: {{ .Values.pgsql.volume_path }}
          env:
            - name: PGDATA
              value: {{ .Values.pgsql.volume_path }}/{{ .Values.pgsql.pg_version }}
  backoffLimit: 10
  completions: 1
