apiVersion: v1
kind: Pod
metadata:
  name: {{ include "citus.fullname" . }}
  labels:
    {{- include "citus.selectorLabels" . | nindent 4 }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  serviceAccountName: {{ include "citus.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 8 }}
  volumes:
    - name: {{ include "citus.fullname" . }}-datadir
      persistentVolumeClaim:
        claimName: {{ include "citus.fullname" . }}-data
  containers:
    - name: {{ .Chart.Name }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      args: ['start']
      env:
        - name: PGDATA
          value: {{ .Values.pgsql.volume_path }}/{{ .Values.pgsql.pg_version }}
      ports:
        - name: pgsql
          containerPort: 5432
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 15
        periodSeconds: 30
      readinessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 5
        periodSeconds: 15
      resources:
        {{- toYaml .Values.resources | nindent 12 }}
      volumeMounts:
        - name: {{ include "citus.fullname" . }}-datadir
          mountPath: {{ .Values.pgsql.volume_path }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}

