apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "citus.fullname" . }}-data
spec:
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pgsql.pvc_size | required "pgsql.pvc_size is required" }}
