apiVersion: v1
kind: Service
metadata:
  name: {{ include "citus.fullname" . }}
  labels:
    {{- include "citus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pgsql
      protocol: TCP
      name: pgsql
  selector:
    {{- include "citus.selectorLabels" . | nindent 4 }}
