apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "citus.fullname" . }}
  labels:
    {{- include "citus.selectorLabels" . | nindent 4 }}
spec:
  serviceName: {{ include "citus.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "citus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "citus.selectorLabels" . | nindent 8 }}
    spec:
      setHostnameAsFQDN: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "citus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["initdb"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "citus.fullname" . }}-datadir
              mountPath: {{ .Values.pgsql.volume_path }}
          env:
            - name: PGDATA
              value: {{ .Values.pgsql.volume_path }}/{{ .Values.pgsql.pg_version }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['start']
          env:
            - name: PGDATA
              value: {{ .Values.pgsql.volume_path }}/{{ .Values.pgsql.pg_version }}
          ports:
            - name: pgsql
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "citus.fullname" . }}-datadir
              mountPath: {{ .Values.pgsql.volume_path }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "citus.fullname" . }}-datadir
      spec:
        storageClassName: {{ .Values.storageClass | default "" }}
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.pgsql.pvc_size | required "pgsql.pvc_size is required" }}

