---
# tasks file for edf6_worker
- name: install deps
  dnf:
    name:
      - mapr-nodemanager
  register: nm_install

- name: refresh config
  command: "/opt/mapr/server/configure.sh -R {{ configure_opts }}"
  when: nm_install.changed == true

- name: start warden
  systemd:
    name: mapr-warden
    state: started
    enabled: false

- name: login
  shell:
    cmd: echo mapr | maprlogin password
  become: true
  become_user: mapr

- name: wait for warden propagation
  wait_for:
    timeout: 60

- name: start service
  shell:
    cmd: "maprcli node services -nodes `hostname` -name {{ item }} -action restart"
  become: true
  become_user: mapr
  with_items:
    - nodemanager
